# Generated by Django 5.1.7 on 2025-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last24Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50)),
                ('hospital_type', models.CharField(max_length=10)),
                ('preauth_initiated_date', models.DateTimeField()),
                ('case_type', models.CharField(max_length=50)),
                ('claim_initiated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50, unique=True)),
                ('hospital_name', models.CharField(max_length=500)),
                ('number_of_surgeons', models.IntegerField(blank=True, null=True)),
                ('number_of_ot', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
