# Generated by Django 5.1.7 on 2025-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0003_last24hour_aco_approved_amount_rs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50, unique=True)),
                ('bed_strength', models.IntegerField()),
            ],
        ),
    ]
