# Generated by Django 5.1.7 on 2025-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0004_hospitalbeds'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['preauth_initiated_date'], name='pmjay_fraud_preauth_63a385_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_id'], name='pmjay_fraud_hospita_5b83b9_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['procedure_code'], name='pmjay_fraud_procedu_abb4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_type'], name='pmjay_fraud_hospita_ff1994_idx'),
        ),
    ]
