# Generated by Django 5.1.7 on 2025-04-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0005_last24hour_pmjay_fraud_preauth_63a385_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_preauth_63a385_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_hospita_5b83b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_procedu_abb4eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_hospita_ff1994_idx',
        ),
    ]
