# Generated by Django 5.1.7 on 2025-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0006_remove_last24hour_pmjay_fraud_preauth_63a385_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbeds',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
