# Generated by Django 5.1.7 on 2025-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0007_hospitalbeds_hospital_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='last24hour',
            unique_together={('registration_id', 'preauth_initiated_date', 'preauth_initiated_time')},
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_type', 'procedure_code'], name='pmjay_fraud_hospita_42e918_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['preauth_initiated_date'], name='pmjay_fraud_preauth_63a385_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['district_name'], name='pmjay_fraud_distric_5a15ef_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['age_years'], name='pmjay_fraud_age_yea_aa7b08_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_code'], name='pmjay_fraud_hospita_86daca_idx'),
        ),
    ]
