# Generated by Django 5.1.7 on 2025-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0008_alter_last24hour_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last24hour',
            name='preauth_initiated_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
