# Generated by Django 5.1.7 on 2025-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0009_alter_last24hour_preauth_initiated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last24hour',
            name='preauth_initiated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
