# Generated by Django 5.1.7 on 2025-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0010_alter_last24hour_preauth_initiated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('suspicious', 'Suspicious Hospital List'), ('beds', 'Hospital Beds')], max_length=20, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
