# Generated by Django 5.1.7 on 2025-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0011_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbeds',
            name='number_of_ot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbeds',
            name='number_of_surgeons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
